version: '3'

services:

  node:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    command: tail -f /dev/null
    working_dir: /app
    environment:
      - YARN_CACHE_FOLDER=/app/node_cache/yarn
    volumes:
      - .:/app
    ports:
      - "8080:8080"
