AWSTemplateFormatVersion: 2010-09-09
Description: Manages domain, CDN, and static website.
Transform: AWS::Serverless-2016-10-31
Parameters:
  DomainName: { Type: String }
  Route53HostedZoneId: { Type: String }
  WildcardCertificateARN: { Type: String }
Resources:
  Domain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt [ CDN, DomainName ]
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Aliases: [ !Ref DomainName ]
        DefaultCacheBehavior:
          TargetOriginId: StaticAssets
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues: { QueryString: true }
        Origins:
          - Id: StaticAssets
            DomainName: !GetAtt StaticAssets.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CDNIdentity}"
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref WildcardCertificateARN
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
  CDNIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${DomainName}"
  StaticAssets:
    Type: AWS::S3::Bucket
  WebsiteAccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssets
      PolicyDocument:
        Statement:
          Effect: Allow
          Action: s3:GetObject
          Principal: { CanonicalUser: !GetAtt CDNIdentity.S3CanonicalUserId }
          Resource: !Sub "${StaticAssets.Arn}/*"
Outputs:
  DomainName: { Value: !Sub "https://${DomainName}" }
  StaticAssetsBucket:
    Description: Contains static assets of website.
    Value: !Ref StaticAssets
  BucketARN: { Value: !GetAtt StaticAssets.Arn }
  DistributionID:
    Value: !Ref CDN
    Description: CloudFront distribution id that servers files from the website.
