name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup environment
        run: make up
      - name: Install depedencies
        run: make install
      - name: Lint
        run: make lint
