name: prod-deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_OUTPUT: ${{ secrets.AWS_DEFAULT_OUTPUT }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: |
          echo ::set-env name=ID::$(id -u)
          echo ::set-env name=GID::$(id -g)
      - name: Up, install dependencies, and test
        run: make up install test
      - name: Build, Deploy, and invalidate CDN
        run: make build deploy cdn