name: test

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup environment
        run: make up
      - name: Install depedencies
        run: make install
      - name: Test
        run: make test